// AUTO-GENERATED by scripts/build-modes.js — do not edit manually
// Run: node scripts/build-modes.js

import { meta as solid_fillMeta, applyStyle as solid_fillStyle } from './solid-fill.js';
import { meta as circleMeta, draw as circleDraw } from './circle.js';
import { meta as squareMeta, draw as squareDraw } from './square.js';
import { meta as diamondMeta, draw as diamondDraw } from './diamond.js';
import { meta as ringsMeta, draw as ringsDraw } from './rings.js';
import { meta as diagonalMeta, draw as diagonalDraw } from './diagonal.js';
import { meta as oceanMeta, draw as oceanDraw } from './ocean.js';
import { meta as frostMeta, draw as frostDraw } from './frost.js';
import { meta as particlesMeta, draw as particlesDraw } from './particles.js';
import { meta as auroraMeta, draw as auroraDraw } from './aurora.js';
import { meta as tendrilsMeta, draw as tendrilsDraw } from './tendrils.js';

export const MODES = [
  { ...solid_fillMeta, type: 'fill', applyStyle: solid_fillStyle },
  { ...circleMeta, type: 'canvas', draw: circleDraw },
  { ...squareMeta, type: 'canvas', draw: squareDraw },
  { ...diamondMeta, type: 'canvas', draw: diamondDraw },
  { ...ringsMeta, type: 'canvas', draw: ringsDraw },
  { ...diagonalMeta, type: 'canvas', draw: diagonalDraw },
  { ...oceanMeta, type: 'canvas', draw: oceanDraw },
  { ...frostMeta, type: 'canvas', draw: frostDraw },
  { ...particlesMeta, type: 'canvas', draw: particlesDraw },
  { ...auroraMeta, type: 'canvas', draw: auroraDraw },
  { ...tendrilsMeta, type: 'canvas', draw: tendrilsDraw },
];
