#!/usr/bin/env node
/**
 * Auto-generates src/modes/index.js from all mode files in src/modes/.
 *
 * Usage: node scripts/build-modes.js
 *
 * Any .js file in src/modes/ (except index.js) that exports `meta` and
 * either `draw` or `applyStyle` will be registered automatically.
 */

import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { join, basename } from 'path';

const MODES_DIR = join(import.meta.dirname, '..', 'src', 'modes');
const INDEX_FILE = join(MODES_DIR, 'index.js');

const files = readdirSync(MODES_DIR)
  .filter(f => f.endsWith('.js') && f !== 'index.js')
  .sort();

const modes = [];

for (const file of files) {
  const content = readFileSync(join(MODES_DIR, file), 'utf-8');
  const name = basename(file, '.js');
  const safeName = name.replace(/[^a-zA-Z0-9]/g, '_');

  const hasDraw = content.includes('export function draw');
  const hasApplyStyle = content.includes('export function applyStyle');
  const hasMeta = content.includes('export const meta');

  if (!hasMeta) {
    console.warn(`Skipping ${file}: no exported meta`);
    continue;
  }

  // Extract order from meta (default: 99 = appended at end)
  const orderMatch = content.match(/order:\s*(\d+)/);
  const order = orderMatch ? parseInt(orderMatch[1]) : 99;

  const importParts = [`meta as ${safeName}Meta`];
  if (hasDraw) importParts.push(`draw as ${safeName}Draw`);
  if (hasApplyStyle) importParts.push(`applyStyle as ${safeName}Style`);

  const importLine = `import { ${importParts.join(', ')} } from './${file}';`;

  const type = hasDraw ? 'canvas' : 'fill';
  const extra = [];
  if (hasDraw) extra.push(`draw: ${safeName}Draw`);
  if (hasApplyStyle) extra.push(`applyStyle: ${safeName}Style`);

  const entryLine = `  { ...${safeName}Meta, type: '${type}'${extra.length ? ', ' + extra.join(', ') : ''} },`;

  modes.push({ order, importLine, entryLine, file });
}

// Sort by order field, then by filename
modes.sort((a, b) => a.order - b.order || a.file.localeCompare(b.file));

const imports = modes.map(m => m.importLine);
const entries = modes.map(m => m.entryLine);

const output = `// AUTO-GENERATED by scripts/build-modes.js — do not edit manually
// Run: node scripts/build-modes.js

${imports.join('\n')}

export const MODES = [
${entries.join('\n')}
];
`;

writeFileSync(INDEX_FILE, output);
console.log(`Generated ${INDEX_FILE} with ${modes.length} modes`);
